// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageWebApp.Models;

namespace MultiPageWebApp.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MultiPageWebApp.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "65 Lake St, Urbandale IA, 50256",
                            Name = "Bob Dylan",
                            Note = "Concert",
                            Number = "5154462487"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "523 Fake St, Johnston IA, 50263",
                            Name = "Jon Rogers",
                            Note = "Plumber",
                            Number = "5154569577"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "102 Jutland Ave, Clive IA, 50325",
                            Name = "Jake Bransgrove",
                            Note = "WBHS",
                            Number = "5157784255"
                        },
                        new
                        {
                            ContactId = 4,
                            Address = "99 Island Road, Adel IA, 50893",
                            Name = "Grant Buchanan",
                            Note = "Best bud",
                            Number = "6634552258"
                        },
                        new
                        {
                            ContactId = 5,
                            Address = "72 Lakeside Road, Ankeny IA, 50882",
                            Name = "Dad",
                            Note = "",
                            Number = "5622458855"
                        },
                        new
                        {
                            ContactId = 6,
                            Address = "122 NW 80th, Urbandale IA, 50332",
                            Name = "Mum",
                            Note = "",
                            Number = "5625682253"
                        },
                        new
                        {
                            ContactId = 7,
                            Address = "1660 NW 75th St, Clive IA 50325",
                            Name = "Abby",
                            Note = "Fiancee",
                            Number = "5159793742"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
